name: MoreCommandsPlus
version: '${project.version}'
main: xyz.wendyscraft.morecommandsplus.MoreCommandsPlus
api-version: 1.18
authors: [ Cosmic_Burger ]
description: An Improved Version of MoreCommandsPlus
commands:
  god:
    description: Makes the Player Invinsible
    usage: /<command>
    aliases:
      - invincible
      - pro
    permission: morecommandsplus.god
  feed:
    description: Full the players Hunger
    usage: /<command>
    permission: morecommandsplus.feed
  printMessageFromConfig:
    description: Command that shows config
    usage: /<command>
    permission: morecommandsplus.printmessagefromconfig
  heal:
    description: Heals The player to max hearts
    usage: /<command>
    permission: morecommandsplus.heal
  fly:
    description: Allows for flight of the Player
    usage: /<command>
    permission: morecommandsplus.fly
  repeat:
    description: Allows to repeat
    usage: /<command>
    permission: morecommandsplus.repeat
  printfood:
    description: Prints the food from the config
    usage: /<command>
    permission: morecommandsplus.printfood
  setspawn:
    description: Sets the servers Spawnpoint
    usage: /<command>
    permission: morecommandsplus.setspawn
  spawn:
    description: Allows the Player to teleport to spawn
    usage: /<command>
    permission: morecommandsplus.spawn
  vault:
    description: Open the players vault
    usage: /<command>
    permission: morecommandsplus.vault
  enderchest:
    description: Opens the users ender chest
    usage: /<command>
    permission: morecommandsplus.vault
    aliases:
      - ec
      - echest
      - enderc
